services:
  postgres:
    image: postgres:17
    container_name: orderflow-postgres
    environment:
      POSTGRES_USER: orderflow
      POSTGRES_PASSWORD: orderflow
      POSTGRES_DB: orderflow
    ports:
      - "5432:5432"
    volumes:
      - orderflow-postgres-data:/var/lib/postgresql/data

  postgres-test:
    image: postgres:17
    container_name: orderflow-postgres-test
    environment:
      POSTGRES_USER: orderflow
      POSTGRES_PASSWORD: orderflow
      POSTGRES_DB: orderflow_test
    ports:
      - "5433:5432"

  api:
    build:
      context: .
      dockerfile: src/OrderFlow.Api/Dockerfile
    container_name: orderflow-api
    environment:
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=orderflow;Username=orderflow;Password=orderflow
      Jwt__Key: orderflow-local-docker-secret-key-change-me
      Jwt__Issuer: OrderFlow
      Jwt__Audience: OrderFlow
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  orderflow-postgres-data:
