services:
  postgres:
    image: postgres:17
    container_name: orderflow-postgres
    environment:
      POSTGRES_USER: orderflow
      POSTGRES_PASSWORD: orderflow
      POSTGRES_DB: orderflow
    ports:
      - "5432:5432"
    volumes:
      - orderflow-postgres-data:/var/lib/postgresql/data

  postgres-test:
    image: postgres:17
    container_name: orderflow-postgres-test
    environment:
      POSTGRES_USER: orderflow
      POSTGRES_PASSWORD: orderflow
      POSTGRES_DB: orderflow_test
    ports:
      - "5433:5432"

volumes:
  orderflow-postgres-data:
